In [32]:
import resnet_model
import tensorflow as tf
import cifar10_input
import cifar10_with_resnet_model
import project_utils

In [33]:
tf.reset_default_graph()
input_data = cifar10_input.Cifar10DataSet("/var/ellie/data/cifar10_tfr/", subset="eval", use_distortion=False)
imgs, lbls = input_data.make_batch(10)

In [34]:
model = cifar10_with_resnet_model.ResNetCifar10(
    44,
    batch_norm_decay=0.997,
    batch_norm_epsilon=1e-5,
    is_training=False,
    data_format='channels_last')
logits = model.forward_pass(imgs, input_data_format='channels_last')
predictions = {
    'classes': tf.argmax(input=logits, axis=1),
    'probabilities': tf.nn.softmax(logits)
}

In [35]:
allvars = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
var_map = {"neural_network/" + v.name.split(':')[0]: v for v in allvars}
tf.train.init_from_checkpoint("/var/ellie/models/cifar10_new/model.ckpt-50000", var_map)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        _lbls, _preds = sess.run([lbls, predictions['classes']])
        print(_lbls, _preds)   

[3 8 8 0 6 6 1 6 3 1] [3 8 8 0 6 6 3 6 3 1]
[0 9 5 7 9 8 5 7 8 6] [0 9 5 7 9 8 5 7 8 6]
[7 0 4 9 5 2 4 0 9 6] [5 0 4 9 5 2 4 0 9 6]
[6 5 4 5 9 2 4 1 9 5] [6 5 4 5 9 3 4 1 9 5]
[4 6 5 6 0 9 3 9 7 6] [4 6 5 6 0 9 3 9 7 6]
[9 8 0 3 8 8 7 7 4 6] [9 8 0 3 8 8 7 3 7 3]
[7 3 6 3 6 2 1 2 3 7] [7 5 6 3 6 2 1 2 3 4]
[2 6 8 8 0 2 9 3 3 8] [2 6 8 8 0 2 9 3 5 8]
[8 1 1 7 2 5 2 7 8 9] [8 1 1 7 2 5 2 7 8 9]
[0 3 8 6 4 6 6 0 0 7] [0 3 8 6 4 6 6 0 0 7]
